/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-tertiary": "#ffffff",
        "on-primary-container": "#769682",
        tertiary: "#0f1500",
        "inverse-on-surface": "#f4f0e7",
        "inverse-surface": "#31312a",
        "on-tertiary-fixed-variant": "#3d4d00",
        "secondary-fixed": "#ffdbcf",
        error: "#ba1a1a",
        "tertiary-fixed": "#d0ef67",
        "on-secondary": "#ffffff",
        "surface-container-highest": "#e6e2d8",
        "on-primary-fixed": "#022113",
        "on-primary-fixed-variant": "#2f4d3c",
        "surface-dim": "#dddad0",
        "on-primary": "#ffffff",
        "error-container": "#ffdad6",
        "primary-fixed-dim": "#adceb8",
        "inverse-primary": "#adceb8",
        "on-secondary-fixed-variant": "#822700",
        "secondary-container": "#d04400",
        "on-background": "#1c1c16",
        secondary: "#a63500",
        "surface-variant": "#e6e2d8",
        "surface-tint": "#476553",
        "on-error-container": "#93000a",
        "secondary-fixed-dim": "#ffb59c",
        "surface-bright": "#fdf9ef",
        "on-error": "#ffffff",
        outline: "#727973",
        "surface-container-high": "#ece8de",
        "on-secondary-container": "#fffbff",
        "tertiary-container": "#212b00",
        background: "#fdf9ef",
        "tertiary-fixed-dim": "#b4d34e",
        "surface-container-low": "#f7f3e9",
        "on-tertiary-container": "#7d9914",
        "surface-container-lowest": "#ffffff",
        "surface-container": "#f1eee4",
        primary: "#00170b",
        surface: "#fdf9ef",
        "on-secondary-fixed": "#390c00",
        "on-tertiary-fixed": "#171e00",
        "primary-container": "#0f2d1e",
        "on-surface": "#1c1c16",
        "outline-variant": "#c2c8c1",
        "on-surface-variant": "#424843",
        "primary-fixed": "#c9ebd3",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "gutter-mobile": "1rem",
        "space-md": "1rem",
        "space-2xl": "4rem",
        "space-sm": "0.5rem",
        "space-xl": "2.5rem",
        "space-lg": "1.5rem",
        "margin-mobile": "1.25rem",
        margin: "3rem",
        "space-xs": "0.25rem",
        gutter: "1.5rem",
      },
      fontFamily: {
        "display-xl-mobile": ["Space Grotesk", "sans-serif"],
        "headline-lg-mobile": ["Space Grotesk", "sans-serif"],
        "body-lg": ["Plus Jakarta Sans", "sans-serif"],
        "display-lg": ["Space Grotesk", "sans-serif"],
        "body-md": ["Plus Jakarta Sans", "sans-serif"],
        "body-sm": ["Plus Jakarta Sans", "sans-serif"],
        "headline-sm": ["Space Grotesk", "sans-serif"],
        "title-md": ["Plus Jakarta Sans", "sans-serif"],
        "display-lg-mobile": ["Space Grotesk", "sans-serif"],
        "display-xl": ["Space Grotesk", "sans-serif"],
        "title-lg": ["Space Grotesk", "sans-serif"],
        "label-sm": ["Space Grotesk", "sans-serif"],
        "label-md": ["Space Grotesk", "sans-serif"],
        "headline-lg": ["Space Grotesk", "sans-serif"],
        "headline-md": ["Space Grotesk", "sans-serif"],
      },
      fontSize: {
        "display-xl-mobile": ["40px", { lineHeight: "44px", letterSpacing: "-0.03em", fontWeight: "700" }],
        "headline-lg-mobile": ["28px", { lineHeight: "34px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "400" }],
        "display-lg": ["56px", { lineHeight: "60px", letterSpacing: "-0.03em", fontWeight: "700" }],
        "body-md": ["15px", { lineHeight: "24px", letterSpacing: "0em", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "18px", letterSpacing: "0em", fontWeight: "400" }],
        "headline-sm": ["22px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "title-md": ["16px", { lineHeight: "22px", letterSpacing: "0em", fontWeight: "600" }],
        "display-lg-mobile": ["34px", { lineHeight: "38px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-xl": ["72px", { lineHeight: "76px", letterSpacing: "-0.04em", fontWeight: "700" }],
        "title-lg": ["18px", { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.06em", fontWeight: "700" }],
        "label-md": ["13px", { lineHeight: "16px", letterSpacing: "0.04em", fontWeight: "700" }],
        "headline-lg": ["40px", { lineHeight: "46px", letterSpacing: "-0.03em", fontWeight: "700" }],
        "headline-md": ["28px", { lineHeight: "34px", letterSpacing: "-0.02em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};
